name: Base Image Build and Release

on:
  push:
    paths:
      - '**/docker-bake.hcl'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: "blacksmith-4vcpu-ubuntu-2204"

    permissions:
      packages: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is available for diff

      - name: Clear space to remove unused folders
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: useblacksmith/build-push-action@v1.1
        with:
          setup-only: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Determine if this is a production build
        id: build_type
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "is_production=true" >> $GITHUB_OUTPUT
          else
            echo "is_production=false" >> $GITHUB_OUTPUT
          fi

      - name: Set environment variables
        run: |
          if [[ "${{ steps.build_type.outputs.is_production }}" != "true" ]]; then
            BRANCH_NAME=$(echo ${GITHUB_REF##refs/heads/} | sed 's/\//-/g')
            echo "RELEASE=dev-${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Get changed docker-bake.hcl files
        id: changed_files
        uses: tj-actions/changed-files@v46
        with:
          json: true
          escape_json: false
          files: |
            **/docker-bake.hcl

      - name: Build and push images
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: docker/bake-action@v6
        env:
          BUILDX_BAKE_ENTITLEMENTS_FS: 0
        with:
          source: .
          files: ./official-templates/base/docker-bake.hcl
          push: true
          set: |
            ${{ steps.build_type.outputs.is_production != 'true' && format('*.args.RELEASE={0}', env.RELEASE) || '' }}
            *.args.GITHUB_WORKSPACE=${{ github.workspace }}
